### ISSUE TITLE
Sidebar nav on MP pages overlaps footer

### ISSUE THREAD

**Issue by andylolz** [mysociety/theyworkforyou#1137] opened 2016-07-14 10:10 UTC
![5aysletesi](https://cloud.githubusercontent.com/assets/464193/16836040/6ca27636-49b3-11e6-899d-b63f1f2a1410.gif)

Don’t know if it’s of any help, but this looks related:
http://foundation.zurb.com/forum/posts/591-set-scrollfixed-limit-for-magellan

**Comment by struan** [comment] 2017-03-03 11:52
Duplicate of #1047

**Closed by struan** 2017-03-03 11:52 UTC
Labels: design
