### ISSUE TITLE
User request: link to question rather than answer

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1107] opened 2016-06-15 08:06 UTC
[presumably for Written answers, possibly for PMQs?]

>When clicking on one of your links in a They Work for You alert, it would be much better if we were directed to the question rather than the answer. The answer itself is rather meaningless without first reading the question. Obviously it is possible to scroll up at the moment - but why should we have to do that every time?

Relates to #277

**Comment by dracos** [comment] 2016-06-15 08:22
Dupe of #60

**Closed by dracos** 2016-06-15 08:22 UTC
