### ISSUE TITLE
[User Suggestion] Link MP statements to fact checkers like Full Fact

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/theyworkforyou#1271] opened 2017-06-09 09:13 UTC
Suggestion from user:

> I’m not sure how possible this is, but i think it would be fascinating to see how many times an MP has appeared on a fact checker and the % of true, false statements that are made.

Could be someone like Full Fact and only for high profile themes that we stick up?

**Comment by abimysoc** [comment] 2017-08-11 14:46
Duplicate of #1171.

**Closed by abimysoc** 2017-08-11 14:46 UTC
