### ISSUE TITLE
User comment: unsubscribe is confusing

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#160] opened 2013-03-11 10:03 UTC
Comment from user: "I tried clicking on the link where it said:

To manage, unsubscribe or add to your alerts, please visit the following link:
    
but it wasn't clear what to do after that!"

MN: Instructions are on the right of the page, and are not the most prominent message on there.

**Comment by struan** [comment] 2015-02-02 18:05
Duplicate of #737

**Closed by struan** 2015-02-02 18:05 UTC
Labels: 1 - Contender, ux
