### ISSUE TITLE
Wrong party affiliation for Baroness Nicholson

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1514] opened 2020-06-11 09:20 UTC
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Hey <a href="https://twitter.com/TheyWorkForYou?ref_src=twsrc%5Etfw">@TheyWorkForYou</a>, I just noticed you list Baroness Nicholson as a Lib Dem Peer but she’s actually a Conservative Peer. <a href="https://t.co/1QMByKViQc">pic.twitter.com/1QMByKViQc</a></p>&mdash; Lucas (@lucasadnorth) <a href="https://twitter.com/lucasadnorth/status/1270996914318782465?ref_src=twsrc%5Etfw">June 11, 2020</a></blockquote>

**Comment by dracos** [comment] 2020-06-11 10:11
Duplicate of https://github.com/mysociety/parlparse/issues/124

**Closed by dracos** 2020-06-11 10:11 UTC
