### ISSUE TITLE
In-page navigation on MP pages looks broken

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/theyworkforyou#1190] opened 2016-11-28 10:17 UTC
Being indented or something? 

![screen shot 2016-11-28 at 10 16 07](https://cloud.githubusercontent.com/assets/2292925/20664620/d9cc1f30-b553-11e6-8d63-94332dcd0c41.png)

**Comment by zarino** [comment] 2017-06-09 09:46
Closing as duplicate of #1203.

**Closed by zarino** 2017-06-09 09:46 UTC
Labels: bug
