### ISSUE TITLE
'less than average' on newer MPs

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1503] opened 2020-02-14 10:04 UTC
A user remarks that in the current circumstances, MPs who took their seat in December and have started speaking are being shown in the numerology section as their contributions to debates as 'below average amongst MPs' and that this is a bit unfair.
'Since joining parliament' does mitigate it a bit, but only if people note their joining date I suppose.

**Comment by dracos** [comment] 2020-02-14 10:07
Duplicate of https://github.com/mysociety/theyworkforyou/issues/1319

**Closed by dracos** 2020-02-14 10:07 UTC
