### ISSUE TITLE
User suggestion: links to legislation.gov.uk instead of wikipedia, where appropriate

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1241] opened 2017-03-22 09:21 UTC
> At https://www.theyworkforyou.com/wrans/?id=2016-12-20.58352.h
the text "Road Traffic Act 1988" links to https://en.wikipedia.org/wiki/Road_Traffic_Act_1988
which unfortunately isn't much use in this instance.

> Given that Government legislation is available online and regularly cited in written questions and answers, could the code that matches phrases with wikipedia then check if there's a better match at legislation.gov.uk ?

> For this written question the ideal solution would have been to link to http://www.legislation.gov.uk/ukpga/1988/52/section/42 from the text "section 42 of the Road Traffic Act 1988"

> I later spotted the "NPIF" acronym in https://www.theyworkforyou.com/wrans/?id=2017-03-09.67263.h
which links to https://en.wikipedia.org/wiki/NPIF (an article on the Northern Patagonian Ice Field)
while there's relevant info in any of these results https://www.google.co.uk/search?q=site:www.gov.uk+npif

> I think automated improvements could be achieved by:
>1. Do existing 'get wiki article titles'
>2. Check if there's an exact match at legislation.gov.uk
>3. Check if there's a certain number of matches at www.gov.uk (this needs the www. and the range could be >0 and eg <50)
>4. Only use the wiki link from 1. if both 2. and 3. fail.

> Matches at 2. would be easy to deal with. I don't have a strong view on whether matches for 3. would be better linking to the top result or a list of results.

> An extra option would be to add:
> 2.1. Scan text of wiki article for mentions of eg 'uk' or 'Government'
> 2.2. Jump to 4. if there are matches that suggest the article is relevant
> These could be done before 2. if testing finds that some legislation.gov.uk results aren't relevant.

> There's also potential to collate the results from 2.1 to analyse the frequency of certain keywords in all linked articles. This could help inform how relevant the current wiki links might be and guide how worthwhile implementation of the above suggestion would be.

**Comment by dracos** [comment] 2019-01-03 10:59
Dupe of #1006.

**Closed by dracos** 2019-01-03 10:59 UTC
